name: 'Argument Counter'
description: 'Count # of arguments passed in'
author: 'Nay Htut Aung'
inputs:
  arguments-to-count: # input id
    description: 'arguments to count'
    required: true
    default: ''
outputs:
  arg-count:
   description: "Count of arguments passed in"
   value: ${{ steps.return-result.outputs.num-args }}
runs:
  using: "composite"
  steps:
    - name: Print arguments if any
      run: echo "Arguments: ${{ inputs.arguments-to-count }}"
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - id: return-result
      run: echo "num-args=`count-args.sh ${{ inputs.arguments-to-count }}`" >> $GITHUB_OUTPUT
      shell: bash
